require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/arquivos', type: :request do
  # Arquivo. As you add validations to Arquivo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Arquivo.create! valid_attributes
      get arquivos_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      arquivo = Arquivo.create! valid_attributes
      get arquivo_url(arquivo)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_arquivo_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      arquivo = Arquivo.create! valid_attributes
      get edit_arquivo_url(arquivo)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Arquivo' do
        expect do
          post arquivos_url, params: { arquivo: valid_attributes }
        end.to change(Arquivo, :count).by(1)
      end

      it 'redirects to the created arquivo' do
        post arquivos_url, params: { arquivo: valid_attributes }
        expect(response).to redirect_to(arquivo_url(Arquivo.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Arquivo' do
        expect do
          post arquivos_url, params: { arquivo: invalid_attributes }
        end.to change(Arquivo, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post arquivos_url, params: { arquivo: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested arquivo' do
        arquivo = Arquivo.create! valid_attributes
        patch arquivo_url(arquivo), params: { arquivo: new_attributes }
        arquivo.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the arquivo' do
        arquivo = Arquivo.create! valid_attributes
        patch arquivo_url(arquivo), params: { arquivo: new_attributes }
        arquivo.reload
        expect(response).to redirect_to(arquivo_url(arquivo))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        arquivo = Arquivo.create! valid_attributes
        patch arquivo_url(arquivo), params: { arquivo: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested arquivo' do
      arquivo = Arquivo.create! valid_attributes
      expect do
        delete arquivo_url(arquivo)
      end.to change(Arquivo, :count).by(-1)
    end

    it 'redirects to the arquivos list' do
      arquivo = Arquivo.create! valid_attributes
      delete arquivo_url(arquivo)
      expect(response).to redirect_to(arquivos_url)
    end
  end
end
