TipoDeTransacao.create(tipo: 1, descricao: 'Débito', natureza: 'Entrada', sinal: true)
TipoDeTransacao.create(tipo: 2, descricao: 'Boleto', natureza: 'Saída', sinal: false)
TipoDeTransacao.create(tipo: 3, descricao: 'Financiamento', natureza: 'Saída', sinal: false)
TipoDeTransacao.create(tipo: 4, descricao: 'Crédito', natureza: 'Entrada', sinal: true)
TipoDeTransacao.create(tipo: 5, descricao: 'Recebimento Empréstimo', natureza: 'Entrada', sinal: true)
TipoDeTransacao.create(tipo: 6, descricao: 'Vendas', natureza: 'Entrada', sinal: true)
TipoDeTransacao.create(tipo: 7, descricao: 'Recebimento TED', natureza: 'Entrada', sinal: true)
TipoDeTransacao.create(tipo: 8, descricao: 'Recebimento DOC', natureza: 'Entrada', sinal: true)
TipoDeTransacao.create(tipo: 9, descricao: 'Aluguel', natureza: 'Saída', sinal: false)