name: CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11@sha256:85d79cba2d4942dad7c99f84ec389a5b9cc84fb07a3dcd3aff0fb06948cdc03b
        ports: ['5432:5432']

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Build and run tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          POSTGRES_PASSWORD: postgres
          RAILS_SECRET_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          ruby --version
          bin/bundle --version
          bin/bundle install --jobs 4 --retry 3
          node --version
          bin/yarn --version
          bin/rails yarn:install webpacker:compile
          bin/ci
